services:
  streamlit:
    build: 
      context: .
      dockerfile: images_docker/Docker_Streamlit/Dockerfile
    container_name: streamlit
    image: spqr_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./temp:/app/temp
      - ./scripts:/app/scripts
      - ./config:/app/config
      - ./output:/data/output
      - /var/run/docker.sock:/var/run/docker.sock  # Add Docker socket mount
    environment:
      - PYTHONPATH=/app
      - PCAP_OUTPUT_DIR=/data/output/pcap
      - HOST_PROJECT_PATH=${HOST_PROJECT_PATH:-${PWD}}
    # Add Docker group to container
    group_add:
      - "${DOCKER_GROUP_ID:-999}"  # Default Docker group ID if not specified
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - suricata6015
      - suricata702
      - snort29
      - snort3

  suricata6015:
    build:
      context: .
      dockerfile: images_docker/Docker_Suricata-6.0.15/Dockerfile
    container_name: suricata6015
    image: spqr_suricata6015
    volumes:
      - ./config/suricata_6.0.15:/etc/suricata
      - ./config/suricata_6.0.15/rules:/etc/suricata/rules
      - ./output/logs:/var/log/suricata
    entrypoint: ["/usr/bin/suricata"]
    command: ["-V"]


  suricata702:
    build:
      context: .
      dockerfile: images_docker/Docker_Suricata-7.0.2/Dockerfile
    container_name: suricata702
    image: spqr_suricata702
    volumes:
      - ./config/suricata_7.0.2:/etc/suricata
      - ./config/suricata_7.0.2/rules:/etc/suricata/rules
      - ./output/logs:/var/log/suricata
    entrypoint: ["/usr/bin/suricata"]
    command: ["-V"]

  snort29:
    build:
      context: ./images_docker/Docker_Snort-2.9
      dockerfile: Dockerfile
    container_name: snort29
    image: spqr_snort29  # Changed to match the Python code
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output

  snort3:
    build:
      context: ./images_docker/Docker_Snort-3
      dockerfile: Dockerfile
    image: spqr_snort3  # Changed to match the Python code
    container_name: snort3
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output

