version: '3.8'

services:
  streamlit:
    build: 
      context: ./images_docker/Docker_Streamlit
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    container_name: streamlit
    image: spqr_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./spqr_app:/app/spqr_app:ro
      - ./config:/app/config:ro
      - ./output:/app/output
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - suricata6015
      - suricata702
      - snort29
      - snort3

  suricata6015:
    build:
      context: ./images_docker/Docker_Suricata-6.0.15
      dockerfile: Dockerfile
    container_name: suricata6015
    image: spqr_suricata_6.0.15
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output
    entrypoint: ["/usr/bin/suricata"]
    command: ["-V"]


  suricata702:
    build:
      context: ./images_docker/Docker_Suricata-7.0.2
      dockerfile: Dockerfile
    container_name: suricata702
    image: spqr_suricata_7.0.2
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output
    entrypoint: ["/usr/bin/suricata"]
    command: ["-V"]

  snort29:
    build:
      context: ./images_docker/Docker_Snort-2.9
      dockerfile: Dockerfile
    container_name: snort29
    image: spqr_snort_2.9
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output

  snort3:
    build:
      context: ./images_docker/Docker_Snort-3
      dockerfile: Dockerfile
    image: spqr_snort_3
    container_name: snort3
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output

