version: '3.8'

services:
  streamlit:
    build: 
      context: ./spqr_app
      dockerfile: DOCKERFILE
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - suricata6015
      - suricata702
      - snort29
      - snort3

  suricata6015:
    build:
      context: ./images_docker/Docker_Suricata-6.0.15
      dockerfile: Dockerfile
    container_name: suricata6015
    image: spqr_suricata_6.0.15
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output
    entrypoint: ["/usr/bin/suricata"]
    command: ["-V"]


  suricata702:
    build:
      context: ./images_docker/Docker_Suricata-7.0.2
      dockerfile: Dockerfile
    container_name: suricata702
    image: spqr_suricata_7.0.2
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output
    entrypoint: ["/usr/bin/suricata"]
    command: ["-V"]

  snort29:
    build:
      context: ./images_docker/Docker_Snort-2.9
      dockerfile: Dockerfile
    container_name: snort29
    image: spqr_snort_2.9
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output

  snort3:
    build:
      context: ./images_docker/Docker_Snort-3
      dockerfile: Dockerfile
    image: spqr_snort_3
    container_name: snort3
    volumes:
      - ./config:/data/config:ro
      - ./input:/data/input:ro
      - ./output:/data/output

