version: '3.8'

services:
  streamlit:
    build: ./spqr_app
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./SPQR:/app
    depends_on:
      - suricata6015
      - snort2
      - snort3

  suricata6015:
    build:
      context: ./images_docker/Docker_Suricata-6.0.15
      dockerfile: Dockerfile
    container_name: suricata-6.0.15
    volumes:
      - ./SPQR:/data

  suricata702:
    build:
      context: ./images_docker/Docker_Suricata-7.0.2
      dockerfile: Dockerfile
    container_name: suricata-7.0.2
    volumes:
      - ./SPQR:/data

  snort2:
    build:
      context: ./images_docker/Docker_Snort-2.9
      dockerfile: Dockerfile
    container_name: snort-2.9
    volumes:
      - ./SPQR:/data

  snort3:
    image: ciscotalos/snort3
    container_name: snort-3
    volumes:
      - ./SPQR:/data
