%YAML 1.1
---
# Configuration SPQR pour Suricata

# Règles
default-rule-path: config/
rule-files:
  - suricata.rules

# Sorties
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: output/logs/eve.json
      types:
        - alert
        - http
        - dns
        - tls

# Configuration réseau
host-mode: auto

# Paramètres de performance
runmode: single

# Logging
logging:
  default-log-level: info
  outputs:
  - console:
      enabled: yes
  - file:
      enabled: yes
      filename: output/logs/suricata.log
